openapi: 3.0.0
info: 
  title: WASAPhoto
  description: |
    This API document describes the functioning of WASAPhoto website
  version: 1.0.0
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user 
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin 
      requestBody:
        description: User details 
        content:
          application/json: 
            schema:
              type: object 
              properties:
                name:
                  type: string 
                  example: Maria 
                  pattern: 'Ë†.*?$'
                  minLength: 3 
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful 
          content:
            application/json: 
              schema:
                type: object 
                properties:
                  identifier: 
                    type: string
                    example: "abcdef012345"
  /users/:
    get:
      tags: ["Users"]
      security:
        - bearerAuth: []
      operationId: getUserProfile
      summary: shows the profile of a specific user
      description: given a username, it displays its profile
      parameters:
        - $ref: "#/components/parameters/Username"
      responses:
        "200":
          description: user found and personal page is displayed
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Profile" }
        "400": { description: user not found }
  /users/{username}:
    parameters:
      - $ref: "#components/parameters/Username" 
    put:
      tags: ["Personal profile"]
      security:
        - bearerAuth: []
      operationId: setMyUserName
      summary: changes the username of the authenticated user 
      description: this operation updates the username of authenticated user
      requestBody:
        description: user's details
        content:
          application/json:
            schema: { $ref: "#/components/schemas/User" }
      responses:
        "200": { description: Username updated successfully }
        "400": { description: Username already in use }
    get:
      tags: ["Personal profile"]
      security:
        - bearerAuth: []
      operationId: getMyStream
      summary: returns stream of current user
      description: shows the stream of the current user
      responses:
        "200": 
          description: stream returned successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Profile" }
        "400": { description: an error occured, please try again later }
  /users/{username}/follow:
    parameters:
      - $ref: "#/components/parameters/Username"
    put:
      tags: ["Follow"]
      security:
        - bearerAuth: []
      operationId: followUser
      summary: follows another user
      description: allows the authorised user to follow another user
      requestBody:
        content:
          application/json:
            schema:  { $ref: "#/components/schemas/User" }
      responses:
        "200":
          description: user followed successfully
          content:
            application/json:
              schema:  { $ref: "#/components/schemas/User" }
        "400": { description: failed to follow this user }
    delete:
      tags: ["Follow"]
      security:
        - bearerAuth: []
      operationId: unfollowUser
      summary: unfollows another user
      description: allows user to unfollow another user
      responses:
        "200": 
          description: user unfollowed successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400": { description: failed to unfollow this user }
  /users/{username}/ban:
    parameters:
      - $ref: "#/components/parameters/Username"
    put:
      tags: ["Ban"]
      security:
        - bearerAuth: []
      operationId: banUser
      summary: bans user 
      description: allows user to ban others
      requestBody:  
        content:
          application/json:
            schema: { $ref: "#/components/schemas/User" }
      responses:
        "200": 
          description: user banned successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400": { description: failed to ban user }
    delete:
      tags: ["Ban"]
      security:
        - bearerAuth: []
      operationId: unbanUser
      summary: unbans user
      description: allows user to remove a ban put previously
      responses:
        "200": 
          description: user unbanned successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400": { description: failed to unban user }
  /photos/:
    post:
      tags: ["Photos"]
      security:
        - bearerAuth: []
      operationId: uploadPhoto
      summary: uploads a new photo in the user profile
      description: |
        method that enables user to add a new photo to his profile
        generating a photo id for the photo
      requestBody:
        content:
          image/png:
            schema: { $ref: "#/components/schemas/Photo" }
      responses:
        "200":
          description: photo uploaded successfully
          content:
            image/png: 
              schema: { $ref: "#/components/schemas/Photo" }
        "400": { description: an error occured, please try again later }
  /photos/{photoId}:
    parameters:
      - $ref: "#/components/parameters/PhotoId"
    delete:
      tags: ["Photos"]
      security:
        - bearerAuth: []
      operationId: deletePhoto
      summary: lets user delete an uploaded photo
      description: enables the user to delete an uploaded photo 
      responses:
        "200": { description: photo deleted successfully }
        "400": { description: error, photo not found }
  /photos/{photoId}/likes:
    parameters:
      - $ref: "#/components/parameters/PhotoId"
    post:
      tags: ["Likes"]
      security:
        - bearerAuth: []
      operationId: likePhoto
      summary: to like a photo
      description: lets the user like a photo 
      requestBody:
        content:
          image/png:
            schema: { $ref: "#/components/schemas/Photo" }
      responses:
        "200": 
          description: photo liked successfully
          content:
            image/png:
              schema:  { $ref: "#/components/schemas/Photo" }
        "400": { description: an errror occured, please try again later }
    delete:
      tags: ["Likes"]
      security:
        - bearerAuth: []
      operationId: unlikePhoto
      summary: unlikes a photo
      description: allows the current user to remove a like from photo
      responses:
        "200": { description: like removed successfully }
        "400": { description: an error occured, please retry later }
  /photos/{photoId}/comments:
    parameters:
      - $ref: "#/components/parameters/PhotoId"
    post:
      tags: ["Comments"]
      security:
        - bearerAuth: []
      operationId: commentPhoto
      summary: to comment a photo
      description: allows user to add a comment to a photo
      requestBody:
        content:
          image/png: 
            schema:  { $ref: "#/components/schemas/Photo" }
          application/json:
            schema: { $ref: "#/components/schemas/Comment" }
      responses:
        "200":
          description: comment added successfully
          content:
            image/png:
              schema:  { $ref: "#/components/schemas/Photo" }
        "400": { description: an error occured, please retry later }
  /photos/{photoId}/comments/{commentId}:
    parameters:
      - $ref: "#/components/parameters/PhotoId"
      - $ref: "#/components/parameters/CommentId"
    delete:
      tags: ["Comments"]
      security:
        - bearerAuth: []
      operationId: uncommentPhoto
      summary: removes a comment
      description: allows user to delete his comment from a photo
      responses:
        "200": { description: comment removed successfully }
        "400": { description: an error occured, please retry later }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      title: User
      description: the object represents a single user
      type: object
      properties:
        username:
          description: username
          type: string
          example: maria77
    Photo:
      title: Photo
      description: this object represents a single picture
      type: object
      properties:
        picture:
          description: the picture uploaded
          type: string
          format: binary
        photoId:
          description: id of a photo
          type: number
          example: 10097
        likes:
          description: represents the number of likes on a given photo
          type: integer
          example: 1
        comments: 
          description: represents the list of comments on a given photo
          type: array 
          items: 
            $ref: "#/components/schemas/Comment"
        dateAndTime:
          description: represents the date and time in which the picture was uploaded
          type: string
          format: date-time 
          example: 2017-07-21T17:32:28Z 
    Profile:
      title: Profile
      description: the object represents the profile of a given user
      type: object
      properties:
        username: { $ref: "#/components/parameters/Username" }
        photos:
          type: array
          items: { $ref: "#/components/schemas/Photo" }
        followers:
          type: array
          items: { $ref: "#/components/schemas/User"}
        following:
          type: array
          items: { $ref: "#/components/schemas/User"}
        posts:
          type: integer
          description: number of photos a user uploaded 
          example: 1
    Comment: 
      title: Comment
      description: this object represents a single comment
      type: object
      properties:
        commentId: { $ref: "#/components/parameters/CommentId"}
        username: { $ref: "#/components/parameters/Username" }
        comment: 
          type: string 
          example: beautiful picture man! 
  parameters:
    Username:
      schema:
        type: string
        example: maria77
      name: username
      in: path
      required: true
      description: the unsername of the user
    PhotoId:
      schema:
        type: number
        example: 10097
      name: photoId
      in: path
      required: true
      description: id of a photo 
    CommentId:  
      schema:
        type: number
        example: 01
      name: commentId
      in: path
      required: true
      description: id of a comment


    
